import { DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ContactSection } from "@/components/ContactSection";
import data from "@data/data.json";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
export const metadata = {
  title: "Aranv Consultancy",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </head>
      <body className={`${dmSans.variable} antialiased`}>
        <Header data={data.Header} />
        {children}
        <ContactSection data={data.contactdata} />
        <Footer data={data.footer} />
      </body>
    </html>
  );
}
